features/AdminManagement/config/routes.rb
AdminManagement::Engine.routes.draw do
  resources :admin_management_users
  resources :sessions

  resources :everyday_recommend

  post "everyday_recommend/recommend" =>"everyday_recommend#recommend_update"

  #root :to => 'sessions#new'
  get "/signin" => 'sessions#new'
  get "/signout" => 'sessions#destroy'
  match "/signup" => 'register#new', :via => :get, :as => 'signup'
  match "/signup" => 'register#create', :via => :post


  root :to => 'login_and_register#index'

  get "/index" => 'login_and_register#index'
  get '/about_us' => 'login_and_register#about_us'
  get '/login' => 'login_and_register#login'
  get '/register' => 'login_and_register#register'
  get '/logout' => 'login_and_register#destroy_session'
  get '/register_phone/:open_id' => 'login_and_register#phone_register'

  scope "/user" do
    get '/confirm' => 'login_and_register#confirm'
    post '/user_inspect' => 'login_and_register#inspect_user'
    post '/create' => 'login_and_register#user_register'
    post '/user_login' => 'login_and_register#user_login'
  end

end

features/AdminManagement/app/models/admin_management/admin_management_user.rb
module AdminManagement
  class AdminManagementUser < ActiveRecord::Base

    attr_accessible :id, :name, :email, :password, :phone, :admin
    validates :email, :format => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}
    validates :name, :email, :phone, :uniqueness => true
    validates :name, :email, :phone, :password, :presence => true


    def self.authenticate(email, submitted_password)
      user = find_by_email(email)
      return nil if user.nil?
      return user if user.has_password?(submitted_password)
    end

    def has_password?(submitted_password)
      password == submitted_password
    end

    def self.not_admin
      user = find_all_by_admin false
      return user
    end

    def self.fetch_user_name id
      find(id).name
    end

    def self.confirm_can_use?(column,content)
      where("#{column} = '#{content}'").blank?
    end

  end
end

features/AdminManagement/app/controllers/admin_management/admin_management_users_controller.rb
require_dependency "admin_management/application_controller"

module AdminManagement
  class AdminManagementUsersController < ApplicationController
    before_action :set_admin_management_user, only: [:show, :edit, :update, :destroy]

    # GET /admin_management_users
    def index
      @admin_management_users = AdminManagementUser.all
    end

    # GET /admin_management_users/1
    def show
    end

    # GET /admin_management_users/new
    def new
      @admin_management_user = AdminManagementUser.new
    end

    # GET /admin_management_users/1/edit
    def edit
    end

    # POST /admin_management_users
    def create
      @admin_management_user = AdminManagementUser.new(admin_management_user_params)

      if @admin_management_user.save
        redirect_to @admin_management_user, notice: 'Admin management user was successfully created.'
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /admin_management_users/1
    def update
      if @admin_management_user.update(admin_management_user_params)
        redirect_to @admin_management_user, notice: 'Admin management user was successfully updated.'
      else
        render action: 'edit'
      end
    end

    # DELETE /admin_management_users/1
    def destroy
      @admin_management_user.destroy
      redirect_to admin_management_users_url, notice: 'Admin management user was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_admin_management_user
        @admin_management_user = AdminManagementUser.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def admin_management_user_params
        params.require(:admin_management_user).permit(:name, :email, :password, :phone, :admin)
      end
  end
end

features/AdminManagement/app/controllers/admin_management/application_controller.rb
module AdminManagement
  class ApplicationController < AdminManagement.BaseControllerClass
  end
end

features/AdminManagement/app/controllers/admin_management/everyday_recommend_controller.rb
require_dependency "admin_management/application_controller"

module AdminManagement
  class EverydayRecommendController < ApplicationController

    def index

      @all_shop_logos = SellerManagement::EverydayRecommend.fetch_all_logos

    end

    def recommend_update

      params["data"].values.each do |recommend|
        SellerManagement::EverydayRecommend.update_recommend_status recommend
      end

      render :text=>"ok"

    end

  end
end

features/AdminManagement/app/controllers/admin_management/login_and_register_controller.rb
require_dependency "admin_management/application_controller"

module AdminManagement
  class LoginAndRegisterController < ApplicationController
    layout "login_and_register"

    def index

      return '/' if current_user.blank?

      redirect_to '/admin_management_users' if current_user.admin == 'admin'

      redirect_to '/seller_management/index' if current_user.admin == 'seller'

      redirect_to '/customer_management/index' if current_user.admin == 'customer'

    end

    def about_us

    end

    def login

    end

    def user_register
      user = AdminManagementUser.new(params[:user])

      if user.save
        session[:user_id] = user.id
        render :json => {:tip=>'save_user', :url=>'/customer_management/index'}
      else
        render :json => {:tip=>'not_save', :url=>'/register'}
      end

    end

    def confirm
      render :text => AdminManagementUser.confirm_can_use?(params[:name],params[:content]) ? 'ok' : 'no'
    end

    def inspect_user
      user = AdminManagementUser.find_by(email:params['email'])

      render :text=> user.blank? ? 'email_wrong':(user.password == params[:password] ? 'right':'password_wrong')
    end

    def user_login
      user = AdminManagementUser.find_by(email:params['email'],password:params['password'])

      if user.present?
        session[:user_id] = user.id
        if user.admin == 'customer'
          render :json => {:tip=>'login_success', :url=>'customer_management/index'}
        end

        if user.admin == 'seller'
          render :json => {:tip=>'login_success', :url=>'seller_management/index'}
        end

        if user.admin == 'admin'
          render :json => {:tip=>'login_success', :url=>'admin_management_users'}
        end
      else
        render :json => {:tip=>'login_failure', :url=>'/login'}
      end
    end

    def destroy_session
      session[:user_id] = nil
      redirect_to '/index'
    end

  end
end

features/AdminManagement/app/controllers/admin_management/register_controller.rb
require_dependency "admin_management/application_controller"

module AdminManagement
  class RegisterController < ApplicationController

    def new
      @user = AdminManagementUser.new
    end

    def create
      @user = AdminManagementUser.new(params[:admin_management_user])
      @user.save

      verify_code = generate_verify_code @user
      respond_to do |format|
        if @user.save
          MailerService.welcome_email(@user,verify_code).deliver
          save_user_id_to_session @user
          format.html { redirect_to signin_path, notice: 'User was successfully created.' }
          format.json { render json: @user, status: :created, location: @user }
        else
          format.html { render action: "new" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end

    end

    private

    def generate_verify_code user
      verify_code = (rand(899999)+100000).to_s
      #user_verify_code = FinanceStarUsers::UserVerifyCode.find_by(user_id:user.id)
      #if user_verify_code.nil?
      #  user_verify_code = FinanceStarUsers::UserVerifyCode.create(user_id:user.id,code:verify_code)
      #end
      #user_verify_code.code
    end

    def save_user_id_to_session user
      session[:user_id] = user.id
    end


  end
end

features/AdminManagement/app/controllers/admin_management/sessions_controller.rb
require_dependency "admin_management/application_controller"

module AdminManagement
  class SessionsController < ApplicationController

    def new
      redirect_by_role current_user if signed_in?
    end

    def create
      user = AdminManagementUser.authenticate(params[:session][:email], params[:session][:password])
      if user.nil?
        redirect_to signin_path
      else
        sign_in user
        redirect_by_role user
      end

    end

    def destroy
      sign_out
      redirect_to signin_path
    end


    private

    def redirect_by_role user
      if user.admin=="admin"
        redirect_to admin_management_users_path
      elsif user.admin=="seller"
        redirect_to AdminManagement.seller_signin_redirect_path
      else
        redirect_to AdminManagement.customer_signin_redirect_path
      end

    end

  end
end

features/AdminManagement/app/helpers/admin_management/admin_management_users_helper.rb
module AdminManagement
  module AdminManagementUsersHelper
  end
end

features/AdminManagement/app/helpers/admin_management/application_helper.rb
module AdminManagement
  module ApplicationHelper
  end
end

features/AdminManagement/app/helpers/admin_management/everyday_recommend_helper.rb
module AdminManagement
  module EverydayRecommendHelper

    def fetch_seller_name seller_id
      AdminManagement::AdminManagementUser.fetch_user_name seller_id
    end

  end
end

features/AdminManagement/app/views/admin_management/admin_management_users/_form.html.haml
= form_for(@admin_management_user) do |f|
  -if @admin_management_user.errors.any?
    #error_explanation
      %h2
        = pluralize(@admin_management_user.errors.count, "error")
        prohibited this admin_management_user from being saved:

      %ul
        -@admin_management_user.errors.full_messages.each do |msg|
          %li= msg

  .pull-right
    .actions
      = f.submit :value=>"保存", :class=>"btn btn-primary btn-sm "
  .row
    .col-sm-4
      %h4 账户信息
      %hr
      .field.admin-useredit.clearfix
        = f.label :name, "姓名"
        = f.text_field :name, :class=>'col-sm-7'
      .field.admin-useredit.clearfix
        = f.label :email, "邮箱"
        = f.text_field :email, :class=>'col-sm-7'
      .field.admin-useredit.clearfix
        = f.label :phone, "电话"
        = f.text_field :phone, :class=>'col-sm-7'
      .field.admin-useredit.clearfix
        = f.label :password, "密码"
        = f.text_field :password, :class=>'col-sm-7'

features/AdminManagement/app/views/admin_management/admin_management_users/edit.html.haml
%h3
  编辑账户

= render 'form'

features/AdminManagement/app/views/admin_management/admin_management_users/index.html.erb
<h1>Listing admin_management_users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Phone</th>
      <th>Admin</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_management_users.each do |admin_management_user| %>
      <tr>
        <td><%= admin_management_user.name %></td>
        <td><%= admin_management_user.email %></td>
        <td><%= admin_management_user.password %></td>
        <td><%= admin_management_user.phone %></td>
        <td><%= admin_management_user.admin %></td>
        <td><%= link_to 'Show', admin_management_user %></td>
        <td><%= link_to 'Edit', edit_admin_management_user_path(admin_management_user) %></td>
        <td><%= link_to 'Destroy', admin_management_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin management user', new_admin_management_user_path %>

features/AdminManagement/app/views/admin_management/admin_management_users/index.html.haml
%h3
  账户信息
  .admin-title.pull-right.clearfix
    = link_to '新建用户', new_admin_management_user_path

%table.table
  %thead
    %tr
      %th 姓名
      %th 邮箱
      %th 密码
      %th 电话
      %th 用户权限
      %th
      %th
      %th

  %tbody
    -@admin_management_users.each do |admin_management_user|
      %tr
        %td= admin_management_user.name
        %td= admin_management_user.email
        %td= admin_management_user.password
        %td= admin_management_user.phone
        %td= admin_management_user.admin
        %td= link_to '详细信息', admin_management_user
        %td= link_to '编辑', edit_admin_management_user_path(admin_management_user)
        %td= link_to '删除', admin_management_user, method: :delete, data: { confirm: 'Are you sure?' }
%br

features/AdminManagement/app/views/admin_management/admin_management_users/new.html.haml
%h3
  新建账户

= render 'form'

features/AdminManagement/app/views/admin_management/admin_management_users/show.html.haml
%p#notice
  = notice

.row
  %br
  .col-sm-4
    %h4 账户信息
    %hr
    .admin-useredit.clearfix
      %label 姓名:
      %span= @admin_management_user.name
    .admin-useredit.clearfix
      %label 邮箱:
      %span= @admin_management_user.email
    .admin-useredit.clearfix
      %label 电话:
      %span= @admin_management_user.phone
    .admin-useredit.clearfix
      %label 密码:
      %span= @admin_management_user.password
    .admin-useredit.clearfix
      %label 权限:
      %span= @admin_management_user.admin